test: add test cases
Signed-off-by: Junjie Gao <junjiegao@microsoft.com>

diff --git a/test/e2e/action.yml b/test/e2e/action.yml
--- a/test/e2e/action.yml
+++ b/test/e2e/action.yml
@@ -119,6 +119,26 @@ runs:
         target_artifact_reference: localhost:5000/hello-world:v1
         signature_format: cose
         plugin_config: 'ca_certs=./test/e2e/certs/cert-bundle.pem'
+
+    # failed test cases
+    - name: invalid certificate version
+      continue-on-error: true
+      id: invalid-certificate-version
+      uses: notaryproject/notation-action/sign@v1
+      with:
+        plugin_name: azure-kv
+        plugin_url: ${{ inputs.pluginDownloadURL }}
+        plugin_checksum: ${{ inputs.pluginChecksum }}
+        key_id: https://acrci-test-kv.vault.azure.net/keys/self-signed-pem/invalid
+        target_artifact_reference: localhost:5000/hello-world:v1
+        signature_format: cose
+        plugin_config: 'self_signed=true'
+    - name: 'Should Fail: invalid certificate version'
+      if: steps.invalid-certificate-version.outcome != 'failure'
+      run: |
+          echo "invalid certificate version should failed, but succeeded."
+          exit 1
+      shell: bash
     - name: partial pem cert chain with local invalid local cert bundle
       continue-on-error: true
       id: partial-pem-cert-chain-invalid-local-cert-bundle
